In [1]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm,t,uniform,f
from sklearn.linear_model import LinearRegression
import termcolor
from numba import jit

def rprint(string):
    print(termcolor.colored(string, color='green'))

In [17]:
def RSS(X, model):
    ret=0
    for i in X:
        ret+=(i[:-1]@model[1:].T+model[0]-i[-1])**2
    return ret


def TSS(X):
    ret=np.sum((X[:,-1]-np.sum(X[:,-1])/len(X))**2)
    return ret


In [14]:
Y=np.array([83,85,
           84,85,85,86,86,87,
           86,87,87,87,88,88,88,88,88,89,90,
           89,90,90,91,
           90,92])
X=np.zeros((len(Y),5))
X[0:2,0]=1
X[2:8,1]=1
X[8:19,2]=1
X[19:23,3]=1
X[23:25,4]=1
X,Y

(array([[1., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 1.]]),
 array([83, 85, 84, 85, 85, 86, 86, 87, 86, 87, 87, 87, 88, 88, 88, 88, 88,
        89, 90, 89, 90, 90, 91, 90, 92]))

In [15]:
F=X.T@X
F_1=np.linalg.inv(F)
F,F_1

(array([[ 2.,  0.,  0.,  0.,  0.],
        [ 0.,  6.,  0.,  0.,  0.],
        [ 0.,  0., 11.,  0.,  0.],
        [ 0.,  0.,  0.,  4.,  0.],
        [ 0.,  0.,  0.,  0.,  2.]]),
 array([[0.5       , 0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.16666667, 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.09090909, 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.25      , 0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.5       ]]))

In [16]:
model=F_1@X.T@Y
model

array([84.        , 85.5       , 87.81818182, 90.        , 91.        ])

In [21]:
Rss=RSS(X, model)
for i in range(5):
    for j in range(i+1,5):
        delta = (model[j]-model[i])/(Rss*(F_1[i,i]+F_1[j,j]))*(len(Y)-5)**2
        rprint(f"  B_{i+1}==B_{j+1} pval = {t.sf(delta,len(Y)-5)}")

  B_1==B_2 pval = 0.4994962524505619
  B_1==B_3 pval = 0.4985533433702338
  B_1==B_4 pval = 0.4982089035674374
  B_1==B_5 pval = 0.49843278929304613
  B_2==B_3 pval = 0.49798501844912185
  B_2==B_4 pval = 0.49758202700883564
  B_2==B_5 pval = 0.49815293222795953
  B_3==B_4 pval = 0.49856712098833356
  B_3==B_5 pval = 0.49879445193941274
  B_4==B_5 pval = 0.49970148287825483
